export * from './title/widget_class'
export * from './scrollBoard/widget_class'
export * from './lineChart/widget_class'
export * from './pieChart/widget_class'
export * from './barChart/widget_class'
